#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Define color variables
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

# Define Unicode icons
checkmark='✔'
crossmark='✖'

echo -e "${yellow}------PRE-COMMIT HOOK START------${no_color}"
echo -e "${yellow}------RUNNING PRE COMMIT HOOK BY InFiNet Code------${no_color}"

# Check if the code needs formatting
if ! dotnet format --verify-no-changes; then
 echo -e "${red}------CODE NEEDS FORMATTING. RUNNING DOTNET FORMAT.....------${no_color}"
 dotnet format
 echo -e "${red}------CODE FORMATED, CHECK CHANGED FILES IN GIT CHANGES AND COMMIT AGAIN------${no_color}"
 exit 1
fi

# Build the project
if ! dotnet build --no-restore; then
 echo -e "${red}------BUILD-FAILED------${no_color}"
 echo -e "${red}------PRE-COMMIT HOOK CANCELED------${no_color}"
 exit 1
fi

# Test the project
if ! dotnet test --verbosity normal --no-restore; then
 echo -e "${red}------TEST-FAILED------${no_color}"
 echo -e "${red}------PRE-COMMIT HOOK CANCELED------${no_color}"
 exit 1
fi

echo -e "${green}------PRE-COMMIT HOOK EXECUTED SUCCESSFULLY ------${no_color}"
echo -e "${green}------PRE-COMMIT HOOK END------${no_color}"
