name: Build and Deploy to Azure Web App 🚀

on:
 push:
    branches:
      - production

env:
 ROOT_DIRECTORY_PATH: 'infinet-code'
 AZURE_APP_NAME: 'infinetcode-project-dojo-api'
 APP_NAME: 'dojo-be-api'
 ENVIRONMENT: 'Production'

jobs:
 build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core 🛠️
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build the App 🏗️
        run: dotnet build --configuration Release

      - name: Compile and Package the App 📦
        run: dotnet publish -c Release -o ${{env.ROOT_DIRECTORY_PATH}}/${{env.AZURE_APP_NAME}}
        
      - name: Upload artifact for deployment job ✈️
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.APP_NAME}}
          path: ${{env.ROOT_DIRECTORY_PATH}}/${{env.AZURE_APP_NAME}}

 deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: ${{env.ENVIRONMENT}}
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job 📡
        uses: actions/download-artifact@v3
        with:
          name: ${{env.APP_NAME}}

      - name: Deploy to Azure Web App 💸
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_APP_NAME}}
          slot-name: ${{env.ENVIRONMENT}}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_218D5DC23A5845DA977DD8C4F2B5D69B }}
          package: .
