name: Format Code

on:
  push:
    branches:
      - development

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install dotnet format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format
        run: dotnet format --check --verbosity normal
